[advisories]
ignore = []

[licenses]
allow = [
  "Apache-2.0",
  "MIT",
]

[bans]
multiple-versions = "deny"
highlight = "all"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [
  "https://github.com/rust-lang/crates.io-index",
]
allow-git = []
